language: cpp
compiler: gcc
sudo: required
dist: trusty
group: deprecated-2017Q4

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
  - sudo apt-get install -qq libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo cmake --build .
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"
    
script:
  - cmake .
  - cmake --build .
  - ctest -V
